// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxKU-cXNnrPCdUQMLoKDfdH192fMzo8L4',
    appId: '1:523615607672:web:6c45b1904ed1eb0a15868d',
    messagingSenderId: '523615607672',
    projectId: 'mad-lab-22422',
    authDomain: 'mad-lab-22422.firebaseapp.com',
    storageBucket: 'mad-lab-22422.firebasestorage.app',
    measurementId: 'G-K1ZZK17YD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm93n3BYStLYlIz-E9T52c3JkkPu8UEVU',
    appId: '1:523615607672:android:37aed5be1fe0bba615868d',
    messagingSenderId: '523615607672',
    projectId: 'mad-lab-22422',
    storageBucket: 'mad-lab-22422.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxKU-cXNnrPCdUQMLoKDfdH192fMzo8L4',
    appId: '1:523615607672:web:24f7a5262982474d15868d',
    messagingSenderId: '523615607672',
    projectId: 'mad-lab-22422',
    authDomain: 'mad-lab-22422.firebaseapp.com',
    storageBucket: 'mad-lab-22422.firebasestorage.app',
    measurementId: 'G-7E89N82CZF',
  );
}
